### ISSUE TITLE
Infinite initialisation in chartboost 9.1.0

### ISSUE THREAD

**Issue by mobile-ads-github** [ChartBoost/android-sdk-sample-java#26]
Hello! I faced with problem: on version 9.1.0 when calling 
`Chartboost.startWithAppId(context, appId, appSignature) { startError -> /* some code */ }`
my startCallback is never called. Also when I tried to load ad it says `SESSION NOT STARTED with exception null`. I roll back to version 9.0.0 and initialisation starts working. Сan you fix this?

**Comment by stosiarz** [comment]
Fixed in 9.1.1. Thanks

**Comment by mobile-ads-github** [comment]
Thank you!
