### ISSUE TITLE
Minimum supported API

### ISSUE THREAD

**Issue by kkarunakaran** [ChartBoost/android-sdk-sample-java#8]
Version 8.0.1 release notes say "The Chartboost Android SDK now requires API level 21 (Android OS 5.0) or higher." Does it mean it won't show any ads for API below level 21. We would be losing some users if that's the case. 

Also build.grade of the sample projects has minSdkVersion as 16. Shouldn't it be 21?

**Comment by stosiarz** [comment]
Correct, minimum supported version is 21. You can still use it if your minimum supported version is below 21 but we won't show any ads for api < 21
